# Generated by Django 3.2 on 2024-04-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopassageiro',
            name='id_user',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
