# Generated by Django 3.2 on 2024-04-28 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomotorista',
            name='cnh',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuariomotorista',
            name='ra',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='UsuarioAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ra', models.PositiveSmallIntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
