# Generated by Django 3.2 on 2024-04-28 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20240428_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioAluno',
            new_name='UsuarioPassageiro',
        ),
    ]
