# Generated by Django 3.2 on 2024-04-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_associacaodecarona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociacaoDeCarona',
        ),
        migrations.DeleteModel(
            name='GrupoDeCarona',
        ),
    ]
