# Generated by Django 3.2 on 2024-04-29 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_de_caronas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacaodecarona',
            name='id_carona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grupos_de_caronas.grupodecarona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associacaodecarona',
            name='id_passageiro',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='grupodecarona',
            name='localizacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grupodecarona',
            name='localizacao_desembarque',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='grupodecarona',
            name='localizacao_embarque',
            field=models.CharField(max_length=150),
        ),
    ]
