# Generated by Django 3.2 on 2024-04-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_de_caronas', '0002_auto_20240428_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacaodecarona',
            name='id_passageiro',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
