# Generated by Django 3.2 on 2024-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_de_caronas', '0004_alter_associacaodecarona_id_passageiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupodecarona',
            name='id_motorista',
            field=models.CharField(max_length=28),
        ),
    ]
