# Generated by Django 3.2 on 2024-05-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacoes', '0001_initial'),
        ('grupos_de_caronas', '0005_alter_grupodecarona_id_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodecarona',
            name='id_localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacoes.localizacao'),
            preserve_default=False,
        ),
    ]
